{% set version = "0.2.0" %}
{% set sha256 = "" %}

package:
  name: harpy
  version: '{{ version }}'

source:
  url: https://github.com/pdimens/harpy/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  noarch: generic

requirements:
  build:
  host:
  run:
    - bcftools
    - bioconductor-complexheatmap
    - bwa
    - datamash
    - ema >= 0.7
    - fastp
    - hapcut2
    - naibr-plus
    - libzlib
    - leviathan
    - llvm-openmp 
    - multiqc
    - python >=3.7
    - r-base >=4
    - r-circlize
    - r-dplyr
    - r-dt
    - r-ggplot2
    - r-knitr
    - r-magrittr
    - r-plotly
    - r-rmarkdown
    - r-stitch
    - r-tidyr
    - r-viridislite
    - rich-click
    - snakemake >=7
    - sambamba
    - samtools
    - seqfu
    - tabix
    - zlib

test:
  commands:
    - "snakemake --version"
    - "R --version"
    - "harpy --version"
about:
  home: "https://github.com/pdimens/harpy/"
  license: "The MIT License (MIT)"
  summary: "Process raw haplotagging data, from raw sequences to phased haplotypes."
  doc_url: https://pdimens.github.io/harpy/
  dev_url: https://github.com/pdimens/harpy

extra:
  container:
    extended-base: True
  maintainers:
    - pdimens