# Configuration file for HARPY #

# Number of barcode bins for EMA (higher is more accurate, less performant)
EMA_bins: 500

# Genome to align reads to, in FASTA format
genome_file: genome.fasta

# Directory with untrimmed sequences
raw_seqs: RawSequences
