{% set version = "0.1.0" %}
#{% set sha256 = "18e996232ee607114bd8c7b3be9023af4b7c33517ec76931b266b30cc8943858" %}

package:
  name: harpy
  version: '{{ version }}'

#source:
  #url: https://github.com/pdimens/HARPY/releases/tag/{{ version }}.tar.gz
  #sha256: {{ sha256 }}

source:
  git_rev: '{{ version }}'
  git_url: https://github.com/pdimens/HARPY.git

build:
  number: 0
  noarch: generic

requirements:
  build:
    - libgcc
  host:
    - python >=3.6
  run:
    - bwa
    - bcftools
    - fastp
    - htslib
    - hapcut2
    - leviathan
    - multiqc
    - pysam
    - python >=3.9
    - r-base >=4
    - r-dplyr
    - r-dt
    - r-ggplot2
    - r-knitr
    - r-magrittr
    - r-plotly
    - r-rmarkdown
    - r-stitch
    - r-tidyr
    - snakemake
    - samtools
    - sambamba
    - seqfu
    - throttler
    - tabix

test:
  commands:
    - "snakemake --version"
    - "R --version"
about:
  home: "https://github.com/pdimens/HARPY/"
  license: "The GNU General Public License v3.0 (GPL3)"
  summary: "Process raw haplotagging data, from raw sequences to phased haplotypes."
  doc_url: https://pdimens.github.io/HARPY/
  dev_url: https://github.com/pdimens/HARPY

extra:
  container:
    extended-base: True
  maintainers:
    - pdimens