name: Test Align

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'rules/align-**.smk'
      - '**align.py'
      - 'reports/reportBwaGencov.Rmd'
      - 'reports/reportEmaGencov.Rmd'
      - 'reports/reportEmaCount.Rmd'
      - 'reports/reportBxCount.Rmd'
      - 'reports/reportBxStats.Rmd'
      - 'reports/ilities/bxStats.py'
      - 'utilities/countBX.py'
      - 'utilities/makewindows.py'
      - 'test/data/fastq/**'
      - '**align.yml'

  pull_request:
    branches:
      - 'dev'
    paths:
      - '**align**.smk'
      - 'test/data/fastq/**'
      - '**align.yml'

  schedule:
    - cron: '0 0 * * *'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    name: linux64
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: misc/harpyenv.yaml
          cache-environment: true
          post-cleanup: 'all'
      - name: Install harpy
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          misc/buildforCI.sh
        shell: micromamba-shell {0}

      - name: align bwa
        id: alignbwa
        uses: mathiasvr/command-output@v1
        with:
          run: harpy align -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"
          shell: micromamba-shell {0}

      - name: check bwa
        if: contains(steps.alignbwa.outputs.stderr, 'job execution failed')
        run: exit 1

      - name: align ema
        id: alignema
        uses: mathiasvr/command-output@v1
        with:
          run: harpy align --method ema --ema-bins 20 -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"
          shell: micromamba-shell {0}

      - name: check ema
        if: contains(steps.alignbwa.outputs.stderr, 'job execution failed')
        run: exit 1