name: ci

on:
  push:
    branches:
      - 'dev'
    paths-ignore:
      - "*.md"

  pull_request:
    branches:
      - 'dev'
    paths-ignore:
      - "*.md"

  schedule:
    - cron: '0 0 * * *'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    name: linux64
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: misc/harpyenv.yaml
          cache-environment: true
          post-cleanup: 'all'
      - name: Install harpy
        run: python3 -m pip install --no-deps --upgrade build && python3 -m build
      - name: Test harpy
        run: harpy --version
        shell: micromamba-shell {0}