name: ci

on:
  push:
    branches:
      - 'dev'

  pull_request:
    branches:
      - 'dev'

  schedule:
    - cron: '0 0 * * *'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    name: linux64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: harpy
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: /usr/share/miniconda3/envs/harpy
          key: linux-64-conda-${{ hashFiles('misc/harpyenv.yaml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Update environment
        run: mamba env update -n harpy -f misc/harpyenv.yaml
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Update setuptools
        run: pip install setuptools --upgrade
      - name: Install harpy
        run: |
          conda activate harpy
          python -m pip install --no-deps /home/runner/work/harpy/
      - name: Test harpy
        run: harpy --version