name: Regenerate Lockfiles

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'resources/container/*/*.yaml'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'resources/container/*/*.yaml'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    name: linux64
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: workflow/envs/condalock.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: create lockfile
        shell: micromamba-shell {0}
        run: conda-lock --micromamba -f THEYAMLFILE.yaml -p linux-64 --lockfile DESTINATION.lock
        # figure out way to iterate over yaml files