
name: Publish Docs with Retype
on:
  workflow_dispatch:
  push:
    branches:
      - docs

jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs
      - uses: retypeapp/action-build@latest
        with:
          config: /home/runner/work/HARPY/HARPY/
      - uses: retypeapp/action-github-pages@latest
        with:
          branch: retype
          update-branch: true