name: Test Variants SNP

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'workflow/envs/r-env.yaml'
      - 'workflow/envs/variants.snp.yaml'
      - 'workflow/envs/harpy.yaml'
      - 'workflow/rules/snp-mpileup.smk'
      - 'workflow/rules/snp-freebayes.smk'
      - '**snp.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'workflow/report/BcftoolsStats.Rmd'
      - 'workflow/scripts/makewindows.py'
      - 'test/bam/**'
      - '**variants_snp.yml'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'workflow/envs/r-env.yaml'
      - 'workflow/envs/variants.snp.yaml'
      - 'workflow/envs/harpy.yaml'
      - 'workflow/rules/snp-mpileup.smk'
      - 'workflow/rules/snp-freebayes.smk'
      - '**snp.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'workflow/report/BcftoolsStats.Rmd'
      - 'workflow/scripts/makewindows.py'
      - 'test/bam/**'
      - '**variants_snp.yml'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  test_mpileup:
    name: mpileup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: workflow/envs/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
      - name: variants mpileup
        shell: micromamba-shell {0}
        run: harpy snp mpileup -w 150000 -g test/genome/genome.fasta.gz -q test/bam
  test_freebayes:
    name: freebayes
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: workflow/envs/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
      - name: variants freebayes
        shell: micromamba-shell {0}
        run: harpy snp freebayes -w 150000 -g test/genome/genome.fasta.gz -q test/bam